name: msrv

on:
  push:
    branches: [ master, v3 ]
  pull_request:
    branches: [ master, v3 ]
  schedule:
    - cron: "47 5 * * 6"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v6
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@1.63
      - name: Running test script
        run: |
          cargo test
          # Maintain a list of features that happen to work at MSRV here:
          cargo test --features "proxy punycode urlencoding"
